/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    String usrname,usrtype;
            int id,idd;
            String utype;
    public Dashboard() {
        initComponents();
    }
    
    public Dashboard(int id,String usrname,String usrtype) {
        initComponents();
        this.id=id;
        this.usrname=usrname;
        this.usrtype=usrtype;
        name.setText(this.usrname);
        type.setText(this.usrtype);
        idd=this.id;
        utype=type.getText();
        if(utype=="Doctor"){
        patient.setVisible(false);
        cappoint.setVisible(false);
        vpres.setVisible(false);
        citem.setVisible(false);
        cuser.setVisible(false);
        sreport.setVisible(false);
         vdoc.setVisible(false);
        }else if(utype=="Receptionist"){
            vpres.setVisible(false);
            doctor.setVisible(false);
            sreport.setVisible(false);
            vappoint.setVisible(false);
            citem.setVisible(false);
        }else if(utype=="Pharmist"){
            doctor.setVisible(false);
            patient.setVisible(false);
            cappoint.setVisible(false);
            vappoint.setVisible(false);
            cuser.setVisible(false);
             vdoc.setVisible(false);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lout = new javax.swing.JButton();
        patient = new javax.swing.JButton();
        doctor = new javax.swing.JButton();
        cappoint = new javax.swing.JButton();
        vappoint = new javax.swing.JButton();
        vpres = new javax.swing.JButton();
        citem = new javax.swing.JButton();
        cuser = new javax.swing.JButton();
        vdoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sreport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lout.setBackground(new java.awt.Color(0, 102, 102));
        lout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lout.setForeground(new java.awt.Color(255, 255, 255));
        lout.setText("Logout");
        lout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loutActionPerformed(evt);
            }
        });

        patient.setBackground(new java.awt.Color(0, 102, 102));
        patient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        patient.setForeground(new java.awt.Color(255, 255, 255));
        patient.setText("Patient");
        patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientActionPerformed(evt);
            }
        });

        doctor.setBackground(new java.awt.Color(0, 102, 102));
        doctor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        doctor.setForeground(new java.awt.Color(255, 255, 255));
        doctor.setText("Doctor");
        doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorActionPerformed(evt);
            }
        });

        cappoint.setBackground(new java.awt.Color(0, 102, 102));
        cappoint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cappoint.setForeground(new java.awt.Color(255, 255, 255));
        cappoint.setText("Create Appointmet");
        cappoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappointActionPerformed(evt);
            }
        });

        vappoint.setBackground(new java.awt.Color(0, 102, 102));
        vappoint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vappoint.setForeground(new java.awt.Color(255, 255, 255));
        vappoint.setText("View Appointment");
        vappoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vappointActionPerformed(evt);
            }
        });

        vpres.setBackground(new java.awt.Color(0, 102, 102));
        vpres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vpres.setForeground(new java.awt.Color(255, 255, 255));
        vpres.setText("View Prescription");
        vpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vpresActionPerformed(evt);
            }
        });

        citem.setBackground(new java.awt.Color(0, 102, 102));
        citem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        citem.setForeground(new java.awt.Color(255, 255, 255));
        citem.setText("Create Item");
        citem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citemActionPerformed(evt);
            }
        });

        cuser.setBackground(new java.awt.Color(0, 102, 102));
        cuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cuser.setForeground(new java.awt.Color(255, 255, 255));
        cuser.setText("Create User");
        cuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuserActionPerformed(evt);
            }
        });

        vdoc.setBackground(new java.awt.Color(0, 102, 102));
        vdoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vdoc.setForeground(new java.awt.Color(255, 255, 255));
        vdoc.setText("View Doctor");
        vdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patient, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cappoint, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vappoint, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vpres, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(patient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cappoint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(vappoint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(vpres, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(citem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cuser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(vdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("                Faisal Hospital");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
        jLabel1.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel3.setLayout(null);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(name);
        name.setBounds(110, 20, 130, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 20, 80, 30);

        type.setBackground(new java.awt.Color(255, 255, 255));
        type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(type);
        type.setBounds(110, 70, 120, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Type");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 70, 80, 30);

        sreport.setBackground(new java.awt.Color(0, 102, 102));
        sreport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sreport.setForeground(new java.awt.Color(255, 255, 255));
        sreport.setText("Sales Report");
        sreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sreportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(sreport, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(sreport, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loutActionPerformed
        // TODO add your handling code here:
        UserLogin ul=new UserLogin();
        this.setVisible(false);
        ul.setVisible(true);
    }//GEN-LAST:event_loutActionPerformed

    private void patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientActionPerformed
        // TODO add your handling code here:
        Patient pt=new Patient();
        pt.setVisible(true);
    }//GEN-LAST:event_patientActionPerformed

    private void doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorActionPerformed
        // TODO add your handling code here:
        if(utype=="Doctor"){
            new Doctor(idd,utype).setVisible(true);
        }
        
    }//GEN-LAST:event_doctorActionPerformed

    private void cappointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappointActionPerformed
        // TODO add your handling code here:
        Appointment ap=new Appointment();
        ap.setVisible(true);
    }//GEN-LAST:event_cappointActionPerformed

    private void vappointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vappointActionPerformed
        // TODO add your handling code here:
        new ViewAppointment(idd).setVisible(true);
    }//GEN-LAST:event_vappointActionPerformed

    private void vpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vpresActionPerformed
        // TODO add your handling code here:
        ViewPrescription vp=new ViewPrescription();
        vp.setVisible(true);
    }//GEN-LAST:event_vpresActionPerformed

    private void citemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citemActionPerformed
        // TODO add your handling code here:
        Item it=new Item();
        it.setVisible(true);
    }//GEN-LAST:event_citemActionPerformed

    private void cuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuserActionPerformed
        // TODO add your handling code here:
        User usr=new User();
        usr.setVisible(true);
    }//GEN-LAST:event_cuserActionPerformed

    private void vdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdocActionPerformed
        // TODO add your handling code here:
        ViewDoctor vd=new ViewDoctor();
        vd.setVisible(true);
    }//GEN-LAST:event_vdocActionPerformed

    private void sreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sreportActionPerformed
        // TODO add your handling code here:
        SalesReport rse=new SalesReport();
        rse.setVisible(true);
    }//GEN-LAST:event_sreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cappoint;
    private javax.swing.JButton citem;
    private javax.swing.JButton cuser;
    private javax.swing.JButton doctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton lout;
    private javax.swing.JLabel name;
    private javax.swing.JButton patient;
    private javax.swing.JButton sreport;
    private javax.swing.JLabel type;
    private javax.swing.JButton vappoint;
    private javax.swing.JButton vdoc;
    private javax.swing.JButton vpres;
    // End of variables declaration//GEN-END:variables
}
