
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Doctor extends javax.swing.JFrame {

    /**
     * Creates new form Patient
     */
    public Doctor() {
        initComponents();
        connect();
        autoid();
       // patient_tblview();
    }
    int id;
    String utype;
    int newid;
    public Doctor(int id,String utype) {
        initComponents();
        this.id=id;
        this.utype=utype;
        newid=id;
        connect();
        autoid();
       doctor_tblview();
        //JOptionPane.showMessageDialog(this, newid);
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public void connect(){
    
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_hospital?useTimezone=true&serverTimezone=UTC","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    public void autoid(){
    
        try {
            Statement s=con.createStatement();
            rs=s.executeQuery("Select MAX(Docno) from doctor");
            rs.next();
            rs.getString("MAX(Docno)");
            
            if(rs.getString("MAX(Docno)")==null){
                dno.setText("DS001");
            }
            else{
           long id=Long.parseLong(rs.getString("MAX(Docno)").substring(2,rs.getString("MAX(Docno)").length()));
           
           id++;
           dno.setText("DS"+String.format("%03d", id));
           
            }
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    public void doctor_tblview(){
        
        try {
            pst=con.prepareStatement("Select * from doctor where logid=?");
            pst.setInt(1,newid);
            rs=pst.executeQuery();
            
            ResultSetMetaData Rsm=rs.getMetaData();
            int count;
            count=Rsm.getColumnCount();
            
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next()){
                Vector v=new Vector();
                for(int i=1;i<=count;i++){
                    v.add(rs.getString("Docno"));
                    v.add(rs.getString("name"));
                    v.add(rs.getString("special"));
                    v.add(rs.getString("qualification"));
                    v.add(rs.getString("fee"));
                    v.add(rs.getString("phone"));
                    v.add(rs.getString("room"));
                }
                df.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dspec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dqual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dfee = new javax.swing.JTextField();
        dphone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        droom = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 0, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("             Doctor Registration");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 30, 240, 30);

        dno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(dno);
        dno.setBounds(130, 90, 120, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Doctor No");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 90, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Doctor Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 130, 100, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Room no");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 370, 90, 20);
        jPanel2.add(dname);
        dname.setBounds(130, 120, 140, 30);

        jButton1.setBackground(new java.awt.Color(51, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(250, 410, 71, 30);

        add.setBackground(new java.awt.Color(0, 102, 51));
        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add);
        add.setBounds(10, 410, 70, 30);

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(90, 410, 71, 30);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(170, 410, 71, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Specialization");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 180, 90, 20);
        jPanel2.add(dspec);
        dspec.setBounds(130, 170, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Qualification");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 230, 90, 20);
        jPanel2.add(dqual);
        dqual.setBounds(130, 220, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Checkup fee");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 280, 90, 20);
        jPanel2.add(dfee);
        dfee.setBounds(130, 270, 140, 30);
        jPanel2.add(dphone);
        dphone.setBounds(130, 320, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText(" Phone");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 330, 90, 20);
        jPanel2.add(droom);
        droom.setBounds(130, 360, 60, 30);

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor No", "Doctor Name", "Specialization", "Qualification", "Checkup fee", "Phone", "Room no"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
        String dnum=dno.getText();
        String dtname=dname.getText();
        String spec=dspec.getText();
        String qual=dqual.getText();
        String fee=dfee.getText();
        String phone=dphone.getText();
        String room=droom.getValue().toString();
        
        
        
        
         try {
  pst=con.prepareStatement("insert into doctor(Docno,name,special,qualification,fee,phone,room,logid)Values(?,?,?,?,?,?,?,?)");
  pst.setString(1,dnum);
  pst.setString(2,dtname);
  pst.setString(3,spec);
  pst.setString(4,qual);
  pst.setString(5,fee);
  pst.setString(6,phone);
  pst.setString(7,room);
  pst.setInt(8,newid);
  
  pst.executeUpdate();
  
  JOptionPane.showMessageDialog(this, "DoctorAdded Added");
  
  autoid();
  dname.setText("");
  dspec.setText("");
  dqual.setText("");
  dphone.setText("");
  dfee.setText("");
  droom.setValue(0);
  
 
  dname.requestFocus();
  doctor_tblview();
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel df1=(DefaultTableModel)jTable1.getModel();
        int selectindex=jTable1.getSelectedRow();
        
        dno.setText(df1.getValueAt(selectindex,0).toString());
        dname.setText(df1.getValueAt(selectindex,1).toString());
        dspec.setText(df1.getValueAt(selectindex,2).toString());
        dqual.setText(df1.getValueAt(selectindex,3).toString());
        dfee.setText(df1.getValueAt(selectindex,4).toString());
        dphone.setText(df1.getValueAt(selectindex,5).toString());
        droom.setValue(Integer.parseInt(df1.getValueAt(selectindex,6).toString()));
        
        add.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String dnum=dno.getText();
        String dtname=dname.getText();
        String spec=dspec.getText();
        String qual=dqual.getText();
        String fee=dfee.getText();
        String phone=dphone.getText();
        String room=droom.getValue().toString();
        
        
        
        
         try {
  pst=con.prepareStatement("update doctor set name=?,special=?,qualification=?,fee=?,phone=?,room=? where Docno=?");
  
  pst.setString(1,dtname);
  pst.setString(2,spec);
  pst.setString(3,qual);
  pst.setString(4,fee);
  pst.setString(5,phone);
  pst.setString(6,room);
  pst.setString(7,dnum);

  
  pst.executeUpdate();
  
  JOptionPane.showMessageDialog(this, "Doctor Updated");
  
  autoid();
  dname.setText("");
  dspec.setText("");
  dqual.setText("");
  dphone.setText("");
  dfee.setText("");
  droom.setValue(0);
  
 
  dname.requestFocus();
  doctor_tblview();
  add.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String dnum=dno.getText();
        
        try {
  pst=con.prepareStatement("Delete from doctor where Docno=?");
  
  pst.setString(1,dnum);
  
  pst.executeUpdate();
  
  JOptionPane.showMessageDialog(this, "Doctor Deleted");
  
  autoid();
  dname.setText("");
  dspec.setText("");
  dqual.setText("");
  dphone.setText("");
  dfee.setText("");
  droom.setValue(0);
  dname.requestFocus();
  doctor_tblview();
  add.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField dfee;
    private javax.swing.JTextField dname;
    private javax.swing.JLabel dno;
    private javax.swing.JTextField dphone;
    private javax.swing.JTextField dqual;
    private javax.swing.JSpinner droom;
    private javax.swing.JTextField dspec;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
